apiVersion: v1
kind: Namespace
metadata:
  name: zerotier
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerotier
  namespace: zerotier
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: zerotier
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: zerotier
    spec:
      containers:
        - image: zerotier/zerotier:1.6.5
          args: ["632ea2908593b9ff"]
          imagePullPolicy: IfNotPresent
          name: kube-zt
          resources: {}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_ADMIN
            privileged: true
