apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: argocd-dotnet-kafka-subscriber
spec:
  template:
    serviceAccountName: workflow
  dependencies:
    - name: github
      eventSourceName: github
      eventName: github-app # argocd-dotnet-kafka-event
  triggers:
    - template:
        name: trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: argocd-dotnet-kafka-
                namespace: workflows
              spec:
                entrypoint: build
                serviceAccountName: workflow
                volumes:
                  - name: regcred
                    secret:
                      secretName: regcred
                      items:
                        - key: .dockerconfigjson
                          path: config.json
                  - name: github-access
                    secret:
                      secretName: github-access
                      items:
                        - key: token
                          path: token
                        - key: user
                          path: user
                        - key: email
                          path: email
                templates:
                  - name: build
                    dag:
                      tasks:
                        - name: build
                          templateRef:
                            name: container-image
                            template: build-kaniko-git
                            clusterScope: true
                          arguments:
                            parameters:
                              - name: repo_url
                                value: "https://github.com/Workquark/argocd-dotnet-kafka-subscriber-deploy"
                              - name: repo_ref
                                value: ""
                              - name: repo_commit_id
                                value: ""
                              - name: container_image
                                value: joydeep1985/argocd-dotnet-kafka-subscriber-deploy
                              - name: container_tag
                                value: "latest"
                  - name: test
                    script:
                      image: alpine
                      command: [sh]
                      source: |
                        echo This is a testing simulation...
                        sleep 5
                      volumeMounts:
                        - name: github-access
                          mountPath: /.github/
          # parameters:
          #   - src:
          #       dependencyName: github
          #       dataKey: body.repository.git_url
          #     dest: spec.templates.0.dag.tasks.0.arguments.parameters.0.value
          #   - src:
          #       dependencyName: github
          #       dataKey: body.ref
          #     dest: spec.templates.0.dag.tasks.0.arguments.parameters.1.value
          #   - src:
          #       dependencyName: github
          #       dataKey: body.after
          #     dest: spec.templates.0.dag.tasks.0.arguments.parameters.2.value
          #   - src:
          #       dependencyName: github
          #       dataKey: body.repository.name
          #     dest: spec.templates.0.dag.tasks.0.arguments.parameters.3.value
          #     operation: append
          #   - src:
          #       dependencyName: github
          #       dataKey: body.after
          #     dest: spec.templates.0.dag.tasks.0.arguments.parameters.4.value
          #   - src:
          #       dependencyName: github
          #       dataKey: body.repository.name
          #     dest: spec.templates.0.dag.tasks.1.arguments.parameters.4.value
          #   - src:
          #       dependencyName: github
          #       dataKey: body.after
          #     dest: spec.templates.0.dag.tasks.1.arguments.parameters.5.value
          #   - src:
          #       dependencyName: github
          #       dataKey: body.repository.name
          #     dest: spec.templates.0.dag.tasks.2.arguments.parameters.4.value
          #   - src:
          #       dependencyName: github
          #       dataKey: body.after
          #     dest: spec.templates.0.dag.tasks.2.arguments.parameters.5.value
