---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - github.com/kubernetes/ingress-nginx/blob/main/deploy/static/provider/cloud/1.23
namespace: ingress-nginx
