---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - github.com/kubernetes/ingress-nginx/tree/main/deploy/static/provider/cloud
namespace: ingress-nginx
